export async function GET() {
  const data = [
    {
      coin: "BTC",
      coinName: "Bitcoin",
      logo: "/logos/btc.png",
      totalHoldings: 0.63776,
      averageBuyPrice: 30000,
      currentPrice: 86520.15,
      totalCurrentValue: 55320.15,
      stcg: { gain: -1200, balance: 0.338 },
      ltcg: { gain: 0, balance: 0.3 },
    },
    {
      coin: "ETH",
      coinName: "Ethereum",
      logo: "/logos/eth.png",
      totalHoldings: 5.6736,
      averageBuyPrice: 1500,
      currentPrice: 1620.15,
      totalCurrentValue: 9324.21,
      stcg: { gain: 55320.15, balance: 2.328 },
      ltcg: { gain: 8239.29, balance: 3.3456 },
    },
    {
      coin: "USDT",
      coinName: "Tether",
      logo: "/logos/usdt.png",
      totalHoldings: 3096.54,
      averageBuyPrice: 1,
      currentPrice: 1.015,
      totalCurrentValue: 3142.21,
      stcg: { gain: -1200, balance: 2011.23 },
      ltcg: { gain: 0, balance: 902.47 },
    },
    {
      coin: "MATIC",
      coinName: "Polygon",
      logo: "/logos/matic.png",
      totalHoldings: 2210,
      averageBuyPrice: 1.1,
      currentPrice: 2.31,
      totalCurrentValue: 4672.12,
      stcg: { gain: -1200, balance: 802 },
      ltcg: { gain: 0, balance: 1408 },
    },
    {
      coin: "LTC",
      coinName: "Litecoin",
      logo: "/logos/ltc.png",
      totalHoldings: 15,
      averageBuyPrice: 60,
      currentPrice: 75.23,
      totalCurrentValue: 1128.45,
      stcg: { gain: 250, balance: 6 },
      ltcg: { gain: 350, balance: 9 },
    },
    {
      coin: "DOGE",
      coinName: "Dogecoin",
      logo: "/logos/doge.png",
      totalHoldings: 15000,
      averageBuyPrice: 0.05,
      currentPrice: 0.08,
      totalCurrentValue: 1200,
      stcg: { gain: 200, balance: 9000 },
      ltcg: { gain: 300, balance: 6000 },
    },
    {
      coin: "SOL",
      coinName: "Solana",
      logo: "/logos/sol.png",
      totalHoldings: 50,
      averageBuyPrice: 20,
      currentPrice: 45,
      totalCurrentValue: 2250,
      stcg: { gain: 500, balance: 20 },
      ltcg: { gain: 700, balance: 30 },
    },
    {
      coin: "AVAX",
      coinName: "Avalanche",
      logo: "/logos/avax.png",
      totalHoldings: 80,
      averageBuyPrice: 10,
      currentPrice: 18.5,
      totalCurrentValue: 1480,
      stcg: { gain: 300, balance: 50 },
      ltcg: { gain: 450, balance: 30 },
    },
    {
      coin: "ADA",
      coinName: "Cardano",
      logo: "/logos/ada.png",
      totalHoldings: 500,
      averageBuyPrice: 0.4,
      currentPrice: 0.6,
      totalCurrentValue: 300,
      stcg: { gain: 50, balance: 300 },
      ltcg: { gain: 80, balance: 200 },
    },
    {
      coin: "XRP",
      coinName: "Ripple",
      logo: "/logos/xrp.png",
      totalHoldings: 1000,
      averageBuyPrice: 0.45,
      currentPrice: 0.55,
      totalCurrentValue: 550,
      stcg: { gain: 70, balance: 600 },
      ltcg: { gain: 90, balance: 400 },
    }
  ];

  return Response.json(data);
}
